import React from 'react'

import { observer } from 'mobx-react'

import { Receiver } from 'react-file-uploader'

@observer
export default class Terms extends React.Component {
    constructor(props) {
        super(props)

        /* Localize store to class object. */
        this.store = this.props.store

        this.state = {
            dataUrl : ''
        }
    }

    render() {
        return <div class="container-fluid">
            <h1>Terms &amp; Conditions</h1>

        	<p>Last modified date: May 18, 2018</p>

        	<p>Acceptance of the Terms of Service</p>
        	<p>The following terms and conditions, together with any documents they expressly incorporate by reference (collectively, these "<span class="policyHeaders">Terms of Service</span>"), govern your access to and use of <a href="https://backpage.com">backpage.bit</a> ("we", "us", "our", ours" and/or the "<span class="policyHeaders">Websites</span>"), including any content, functionality and services offered on or through the Websites, whether as model ("Model") or a registered user ("User"). These Terms of Service apply to the Websites, web pages, interactive features, applications, widgets, blogs, social networks, social network "tabs", or other online or wireless offerings that post a link to these Terms of Service, whether accessed via computer, mobile device or other technology, manner or means.</p>
        	<p>Please read the Terms of Service carefully before you start to use the Websites. By using the Websites or by clicking to accept or agree to the Terms of Service when this option is made available to you, you accept and agree to be bound and abide by these Terms of Service and our Privacy Policy, found at <a href="https://backpage.com">https://backpage.bit/information#privacy</a>, incorporated herein by reference. If you do not want to agree to these Terms of Service or the Privacy Policy, you must not access or use the Websites.</p>
        	<p>If you access or use the Websites, whether you click to accept or not, you agree to all of the various terms in these Terms of Service. If you do not understand all of these Terms of Service, you should consult an attorney before agreeing to any of the Terms of Service.</p>
        	<p>You consent to entering these Terms of Service electronically, and to storage of records related to these Terms of Service in electronic form.</p>
        	<p>When using the Websites, you shall be subject to any posted rules, community guidelines, or policies. Such rules, guidelines, and policies are hereby incorporated by reference into these Terms of Service. We may also offer other Websites that are governed by different Terms of Service.</p>
        	<p><span class="policyHeaders">Ability to Accept Terms of Service</span></p>
        	<p>You affirm that you are at least 18 years of age or the age of majority in the jurisdiction you are accessing the Websites from, and are fully able and competent to enter into the terms, conditions, obligations, affirmations, representations, and warranties set forth in these Terms of Service, and to abide by and comply with these Terms of Service. If you are under 18 or the applicable age of majority, you are not permitted to submit personal information to us or use the Websites. You also represent that the jurisdiction from which you access the Websites does not prohibit the receiving or viewing of sexually explicit content.</p>

        	<p><span class="policyHeaders">Changes to the Terms of Service</span></p>
        	<p>We may modify or revise these Terms of Service from time to time in our sole discretion and you agree to be bound by such modifications or revisions. Although we may attempt to notify you when major changes are made to these Terms of Service, you are expected to periodically review the most up-to-date version found at <a href="backpage.bit/information#terms">https://backpage.bit/information#terms</a>, so you are aware of any changes, as they are binding on you.</p>
        	<p>If we change anything in these Terms of Service, the change will be reflected in the "last modified date". You agree that you will periodically review these terms and refresh the page when doing so. You agree to note the date of the last revision of these terms. If the "last modified" date is unchanged from the last time you reviewed these terms, then they are unchanged. On the other hand, if the date has changed, then there have been changes, and you agree to re-review the terms, and you agree to the new ones.</p>
        	<p>All changes are effective immediately when we post them, and apply to all access to and use of the Websites thereafter. The updated version supersedes any prior versions immediately upon being posted, and the prior version(s) shall have no continuing legal effect. If you do not review new terms as posted, then you agree that you have waived your right to do so, and you are therefore bound by the updated conditions, even if you failed to review the new ones. You are on notice of changes, and your failure to review the amended terms is your own omission. By continuing to use the Websites subsequent to us making available an amended version of these Terms of Service, you thereby acknowledge, agree to and consent to such amendment.</p>
        	<p><span class="policyHeaders">About Our Websites</span></p>
        	<p>The Websites allow for uploading, sharing and general viewing of various types of adult-oriented content by registered and unregistered users, models who desire to share and view visual depictions of adult-oriented content, including sexually explicit images. In addition, the Websites contain texts, messages, files, data, information, images, photos, videos, recordings, materials, code or content of any kind and other materials posted/uploaded by users, models.</p>
        	<p>The Websites may contain links to third party Websites that are not owned or controlled by the Websites. The Websites have no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third party Websites. In addition, the Websites will not and cannot censor or edit the content of any third-party site. By using the Websites you expressly relieve it from all liability arising from your use of any third-party Websites. Accordingly, we encourage you to be aware when you leave the Websites and to read the terms, conditions, and privacy policy of each other Websites that you visit.</p>
        	<p>The Websites are for your personal use and shall not be used for any commercial endeavor except those specifically endorsed or approved by the Websites.</p>
        	<p>This Websites are for adult-oriented content. Other categories of content may be deleted at our discretion.</p>
        	<p>You understand and acknowledge that when using the Websites, you will be exposed to content from a variety of sources, and that the Websites are not responsible for the accuracy, usefulness, safety, or intellectual property rights of or relating to such content. You further understand and acknowledge that you may be exposed to content that is inaccurate, offensive, indecent, or objectionable, and you agree to waive, and hereby do waive, any legal or equitable rights or remedies you have or may have against the Websites with respect thereto, and agree to indemnify and hold the Websites, their site operator, their parent corporation, their respective affiliates, licensors, service providers, officers, directors, employees, agents, successors and assigns, harmless to the fullest extent allowed by law regarding all matters related to your use of the Websites.</p>
        	<p><span class="policyHeaders">Purchasing Content</span></p>
        	<p>You may purchase Content made available to you through the Websites by Models. Purchases can be made by credit cards, and when available, by debit cards, and are processed through our third-party Internet payment service providers. By purchasing any content through the Websites, you hereby consent and agree to abide by such third-party Internet payment service providers’ customer terms and conditions, and privacy policies, and understand that we have no control whatsoever on such customer terms and conditions, and privacy policies. IF YOU CANNOT AGREE to such third-party Internet payment service providers’ customer terms and conditions or privacy policies, DO NOT PURCHASE ANY CONTENT. Purchases are payable in advance. We offer different packages you can choose from. We reserve the right to change Content prices at any time, at our sole discretion and without liability to you. Any purchased Content will not be available in your account in the event that your account is deleted by you or otherwise terminated in accordance with these Terms.</p>
        	<p>No Refunds</p>
        	<p>PAYMENTS ARE NONREFUNDABLE AND THERE ARE NO REFUNDS OR CREDITS FOR PARTIALLY USED PERIODS. We reserve the right (but not the obligation) to refund the purchased amount if there is a technical error to the purchased Content; this is to be determined by us.</p>
        	<p>Cardholder Disputes/Chargebacks</p>
        	<p>All chargebacks are thoroughly investigated and may prevent future purchases with MG Billing given the circumstances. Fraud claims may result in MG Billing contacting your issuer to protect you and prevent future fraudulent charges to your Payment Method.</p>

        	<p><span class="policyHeaders">Accessing the Websites and Account Registration and Security</span></p>
        	<p>We reserve the right to withdraw or amend the Websites, and any service or material we provide on the Websites, in our sole discretion without notice. We will not be liable if for any reason all or any part of the Websites is unavailable at any time or for any period. From time to time, we may restrict access to some parts of the Websites, or the entire Websites, to users, including registered users.</p>
        	<p>You are responsible for:</p>
        	<p>1. making all arrangements necessary for you to have access to the Websites;</p>
        	<p>2. ensuring that all persons who access the Websites through your internet connection are aware of these Terms of Service and comply with them.</p>
        	<p>To access the Websites or some of the resources it offers, you may be asked to provide certain registration details or other information. It is a condition of your use of the Websites that all the information you provide on the Websites is correct, current and complete. You agree that all information you provide to register with this Websites or otherwise, including but not limited to through the use of any interactive features on the Websites, is governed by our Privacy Policy found at <a href="backpage.bit/information#privacy">https://backpage.bit/information#privacy</a>, and you consent to all actions we take with respect to your information consistent with our Privacy Policy.</p>
        	<p>If you choose, or are provided with, a user name, password or any other piece of information as part of our security procedures, you must treat such information as confidential and, you must not disclose it to any other person or entity and you are fully responsible for all activities that occur under your user name or password. You also acknowledge that your account is personal to you and agree not to provide any other person with access to the Websites or portions of it using your user name, password or other security information. You agree to notify us immediately of any unauthorized access to or use of your user name or password or any other breach of security by contacting us at: <a href="mailto:support@taboou.com">support@taboou.com</a>.  You also agree to ensure that you exit from your account at the end of each session. You should use particular caution when accessing your account from a public or shared computer so that others are not able to view or record your password or other personal information. Although the Websites will not be liable for your losses caused by any unauthorized use of your account, you may be liable for the losses of the Websites or others due to such unauthorized use.</p>
        	<p>If you interact with us or with third-party service providers, and you provide information, including account or credit card or other payment information, you agree that all information that you provide will be accurate, complete, and current. You will review all policies and agreements applicable to use of third party services. In the event you use our Websites over mobile devices, you hereby acknowledge that your carrier’s normal rates and fees, such as excess broadband fees will still apply.</p>
        	<p>We have the right to disable any user name, password or other identifier, whether chosen by you or provided by us, at any time in our sole discretion for any or no reason, including if, in our opinion, you have violated any provision of these Terms of Service.</p>
        	<p>You acknowledge that the Websites reserve the right to charge fees for its services and Websites access and to change its fees in its complete and sole discretion.</p>
        	<p><span class="policyHeaders">Limited, Conditional License to Use Our Intellectual Property</span></p>
        	<p>We and our associated logos and names are our trademarks and/or service marks. Other trademarks, service marks, names and logos used on or through the Websites, such as trademarks, service marks, names or logos associated with third party Content providers, are the trademarks, service marks or logos of their respective owners. You are granted no right or license with respect to any of the aforesaid trademarks, service marks or logos.</p>
        	<p>The inclusion of images or text containing the trademarks or service marks or the name or likeness of any person, including any celebrity, does not constitute an endorsement, express or implied, by any such person, of the Websites or vice versa.</p>
        	<p>The Websites and certain materials available on or through the Websites are content we own, authored, created, purchased, or licensed (collectively, our "<span class="policyHeaders">Works</span>"). Our Works may be protected by copyright, trademark, patent, trade secret and/or other laws, and we reserve and retain all rights in our Works and the Websites.</p>
        	<p>We hereby grant you a conditional, royalty-free, limited, revocable, non-sublicensable, and non-exclusive license to access our Websites and Works solely for your personal use in connection with using the Websites.</p>
        	<p>We grant you a conditional and limited license to access, view and display Websites and Works, and to create and display transient copies of the Websites and Works as necessary to view them, conditioned upon your agreement to display the Websites whole and intact as presented by the Websites host, complete with any advertising, to not interfere with the display of any advertising, and to not use ad blocking software of any kind. This limited license is further conditioned upon your agreement not to use any information obtained from or through the Websites to block or interfere with the display of any advertising on the Websites, or for the purpose of implementing, modifying or updating any software or filter lists that block or interfere with the display of any advertising on the Websites. Interference with the display of any advertising on the Websites, use of ad blocking software to block or disable any advertising while viewing the Websites, or use of information obtained from or through the Websites to update any ad blocking software or filter lists, is prohibited, violates the conditions of your limited license to view the Websites and Works and constitutes copyright infringement.</p>
        	<p>You may not otherwise reproduce, distribute, communicate to the public, make available, adapt, publicly perform, link to, or publicly display the Websites and Works or any adaptations thereof unless expressly set forth herein. Such conduct would exceed the scope of your license and constitute copyright infringement.</p>
        	<p>The Websites provides an "Embeddable Player" feature, which you may incorporate into your own Websites for use in accessing the Content on the Websites. You may not modify, build upon or block any portion or functionality of the Embeddable Player in any way, including but not limited to links back to the Websites.</p>
        	<p>The above described license is conditioned on your compliance with these Terms of Service, including, specifically, your agreement to view the Websites whole and intact as presented by the Websites host, complete with any advertising, and shall terminate upon termination of these Terms of Service. If you breach any provision of these Terms of Service, any license you have obtained will be automatically rescinded and terminated. In order to protect our rights some Content made available on the Websites may be controlled by digital rights management technologies, which will restrict how you may use the Content. You must not circumvent, remove, delete, disable, alter or otherwise interfere with any digital rights management technology. Such conduct is prohibited by law.</p>
        	<p>If the Websites allows you to download or otherwise copy our Works, you are not buying or being gifted copies thereof. Instead, you are licensing a limited, revocable, non-sublicensable, and non-exclusive right to possess and use the copies for personal, non-commercial use, subject to specific terms and conditions (the "<span class="policyHeaders">Download License</span>"). Under this Download License you may not thereafter reproduce, distribute, communicate to the public, make available, adapt, publicly perform, or publicly display the Websites and Works or any adaptations thereof unless expressly set forth herein. Such conduct would exceed the scope of your Download License and constitute copyright infringement. At the expiration of your Download License or the termination of these Terms of Service, you will delete or otherwise dispose of all copies of Works in your possession.</p>

        	<p><span class="policyHeaders">Content Posted by Users and Models</span></p>
        	<p>The Websites may contain message boards, chat rooms, personal web pages or profiles, playlists, forums, bulletin boards and other interactive features (collectively, "<span class="policyHeaders">Interactive Services</span>") that allow users to upload, post, create, submit, publish, make available, send, share, communicate, display or transmit to other users or other persons
                (collectively, "<span class="policyHeaders">post</span>") content, data, information, audio and video (whether live or pre-recorded) content, photographs/pictures,
                textual content and other materials, including but not limited to, graphics, messages, comments, memberships and tangible goods provided, sold, offered, posted or otherwise contributed by you to the Websites from time to time or
                content of any kind (collectively, "Content") on or through the Websites.</p>

            <p>As the  Websites’ account holder you may submit Content to the Websites and other Websites linked to the Websites including videos and user comments. You understand that the Websites do not guarantee any confidentiality with respect to any Content you submit.</p>
        	<p>You shall be solely responsible for your own Content and the consequences of posting, uploading, publishing transmitting or otherwise making available your Content on the Websites. You understand and acknowledge that you are responsible for any Content you submit or contribute, and you, not us, have full responsibility for such Content, including its legality, reliability, accuracy and appropriateness. We are not responsible, or liable to any third party, for the content or accuracy of any Content posted by you or any other user of the Websites. We do not control Content you submit or contribute and we do not make any guarantee whatsoever related to Content submitted or contributed by users. Although we sometimes review Content submitted or contributed by users, we are not obligated to do so. Under no circumstances will we be liable or responsible in any way for any claim related to Content submitted or contributed by users.</p>
        	<p>You affirm, represent, and warrant that you own or have the necessary licenses, rights, consents, and permissions to publish Content you submit; and you license to the Websites all patent, trademark, trade secret, copyright or other proprietary rights in and to such Content for publication on the Websites pursuant to these Terms of Service.</p>
        	<p>You further agree that Content you submit to the Websites will not contain third party copyrighted material, or material that is subject to other third party proprietary rights, unless you have permission from the rightful owner of the material or you are otherwise legally entitled to post the material and to grant to the Websites all of the license rights granted herein.</p>
        	<p>For clarity, you retain all of your ownership rights in your Content. However, by submitting Content to the Websites, you hereby grant the Websites a worldwide, irrevocable, perpetual, non-exclusive, royalty-free, sublicenseable and transferable license to use, exploit, reproduce, distribute, prepare derivative works of, display, communicate, and perform the Content in connection with the Websites’s (and its successors’ and affiliates’) business, including without limitation for promoting and redistributing part or all of the Websites (and derivative works thereof) in any media formats and through any media channels. You also waive to the full extent permitted by law any and all claims against us related to moral rights in the Content. In no circumstances will we be liable to you for any exploitation of any Content that you post. You also hereby grant each user of the Websites a non-exclusive, royalty free license to access your Content through the Websites, and to use, reproduce, distribute, display, communicate and perform such Content as permitted through the functionality of the Websites and under these Terms of Service. The above licenses granted by you in video Content you submit to the Websites terminate within a commercially reasonable time after you remove or delete your videos from the Websites. You understand and agree, however, that the Websites may retain, but not display, distribute, or perform, server copies of your videos that have been removed or deleted. The above licenses granted by you in user comments you submit are perpetual and irrevocable.</p>
        	<p>The Websites do not endorse any Content submitted to it by any user or other licensor, or any opinion, recommendation, or advice expressed therein, and the Websites expressly disclaims any and all liability in connection with Content. The Websites does not permit copyright infringing activities and infringement of intellectual property rights on the Websites, and the Websites will remove all Content if properly notified that such Content infringes on another’s intellectual property rights. The Websites reserves the right to remove Content without prior notice.</p>
        	<p>All Content you submit must comply with the Content standards set out in these Terms of Use.</p>
        	<p>If any of the Content that you post to or through the Websites contains ideas, suggestions, documents, and/or proposals to us, we will have no obligation of confidentiality, express or implied, with respect to such Content, and we shall be entitled to use, exploit or disclose (or choose not to use or disclose) such Content at our sole discretion without any obligation to you whatsoever (i.e., you will not be entitled to any compensation or reimbursement of any kind from us under any circumstances).</p>
        	<p>In the process of posting Content to the Websites, you may be asked to provide some personally identifying information, such as your name, address, e-mail address, a password, and other documentation. You may also be asked to provide such information in order to use certain features of the Websites.</p>
        	<p>We will keep a record of the information you provide, including your personally identifiable information. That information may be linked in our records to other information you provide, including Content. We will not provide your name or other personally identifying information to our advertisers or business partners without your permission. Please note that some of the information you provide in registering for and using the Websites, including the name used in registering for and using the Websites or other personally identifying information, may be displayed to other members of the Websites, and may become public. In addition, we may disclose the personally identifying information and documentation you provide in some limited circumstances.</p>

        	<p><span class="policyHeaders">Content Posted by Models</span></p>
        	<p>If you want to become a Model and post Content through the Websites, you must first join our MPP Program and agree to the terms and conditions there and provide true and correct personal information. Once you are a Model, you may upload content to <a href="https://backpage.com">backpage.bit</a>.You must provide true and correct personal information. If the information you provide is not true and correct, you face the immediate termination of your account and you may be subject to legal sanctions. Certain changes to your personal information such as country of residence, name, minimum payout, banking details and screen name can only be made by our staff. Therefore, if your information appears incorrect or needs to be changed you may need to contact our staff to have this done.</p>
        	<p>We may, in our sole discretion, decline your application to join our community of content provider for any reason.</p>
        	<p>You may be asked to provide a valid email address for verification purposes and quality assurance, and you agree that we may send you e-mails, both of a transactional nature and also for commercial and promotional purposes.</p>
        	<p>You will choose your own screen name which must be unique to you, not offensive to others and not in violation of another’s copyright or trademark. You will also choose your password, which you can change later. It is imperative that you do not let anyone else use your account (you must keep your password secret and secure).</p>
        	<p>You may never use anyone else’s account, just as no one can ever use yours.</p>
        	<p>Before you are able to upload and offer any Content for sale, you need to verify your identity and age. In order to do so, you need to submit the following documents in color to us (please submit back and front):</p>
        	<p>1. A Photo ID meaning a Government Issued ID containing your Date of Birth, expiration date, your Photo and your full legal name. This could be, for example, your Driver's License (in countries where a National ID is not mandatory), International Passport, Citizenship Card, State ID, National Passport or your National ID Card.</p>
        	<p>2. A Valid Social Security Number and a copy of your Social Security Card (for tax purposes, USA only)</p>
        	<p>These requirements apply to every person who will appear in any media on your profile.</p>
        	<p>You acknowledge that you are solely responsible for the activity that occurs on your account, and you must immediately notify us if you believe there has been the slightest breach of security or unauthorized use of your account.</p>
        	<p>You will be liable for any losses incurred by us due to the unauthorized use of your account. We are not liable for your losses caused by any unauthorized use of your account and you specifically waive any such claim and agree to defend and indemnify us against any such claims made against it by third parties.</p>
        	<p>To the extent you voluntarily create a user profile to participate in certain select services offered by us, your profile (and its contents) may be searchable by other users registered through the Websites and others partnered or networked with us. Likewise, your profile (and its contents) may be searchable by publicly available search engines.</p>
        	<p><span class="policyHeaders">Model Content</span></p>
        	<p>You have decided to join the community of content contributors as a Model and submit Content. You understand that we do not guarantee any confidentiality with respect to any Content you contribute.</p>
        	<p>Subject to what is permitted under applicable law, you are free to choose the type of Content you produce and post or publish. You shall be solely responsible for your own Content and the consequences of posting or publishing such Content. In connection with Content, you affirm, represent, and/or warrant that: (i) you own or have the necessary licenses, rights, consents, and permissions to use and authorize us to use all patent, trademark, trade secret, copyright, right to privacy, right to publicity, or other proprietary commercial or personal rights in and to any and all your Content to enable inclusion and use of Content in the manner contemplated by the Websites and these Terms of Service, and (ii) you have the written consent, release, and/or permission of each and every identifiable persons in your Content to use the name or likeness of each individual for use in your Content in the manner contemplated by the Websites and these Terms of Service.</p>
        	<p>We are not responsible for any Content that violates a community’s norms or mores. We expect and demand that you comply with all federal, state, provincial and local laws when using the Websites and when submitting or posting Content to the Websites. If you are unsure whether or not Content will violate a law, you are urged to contact an attorney prior to posting the Content. We cannot enforce every jurisdiction’s laws for all Content that is posted to the Websites. As such, we are not responsible for the Content of the Websites.</p>
        	<p>You must evaluate, and bear all risks associated with, the use of any Content, including any reliance on the accuracy, completeness, or usefulness, or lawfulness of such Content. In this regard, you acknowledge that you may not rely on any content created by us or Content transmitted to the Website. You are responsible for all your Content that is uploaded, posted, emailed, transmitted or otherwise made available via the service.</p>
        	<p>If we have a reason to suspect that your Content violates any third party right, including without limitation any copyright, trademark, or property right, we can require you to provide us with written evidence of your ownership of, or right to use, the material in question. If we require such written evidence, you agree to provide it to us within five working days of the date of our request. Your failure to provide us with such required written evidence within that timeframe may lead to the immediate termination of your account, us demanding compensation from you for any accrued costs and damages related to such Content and the immediate suspension of any and all pending payments from us to you.</p>
        	<p>Please note that you may not permit any other person to use your account and that you must immediately inform us of any apparent breach of security, such as loss, theft or unauthorized disclosure or use of a screen name or password.</p>
        	<p><span class="policyHeaders">Models’ Commission</span></p>
        	<p>Models will be entitled to receive the following:</p>
        	<p>(a) Modelhub videos on demand: up to 65% of the revenues generated from the sale of your Content on the Websites net of any applicable sales taxes (such as, but not limited to, Value Added Tax). Within certain limits, you are allowed to set the price at which your Content will be sold.</p>
        	<p>(b) MPP Program – Ad Share Revenue: on free to watch videos on the Websites, a percentage of the ad revenue that the video earns.</p>
        	<p>(c) For each full length videos on the Websites, an amount equal to the (i) the view share fraction of such video during the month and (ii) 15% of the net revenues for such month.</p>
        	<p>We will deduct and withhold from any amounts payable to you under these Terms of Services such amounts as we are directed to deduct and withhold or are required to deduct and withhold with respect to such payment under the provision of any applicable laws (including Value Added Tax or VAT) and remit such deduction and withholding amount to the appropriate governmental entity.</p>
        	<p>You will receive monthly a statement that can be viewed from the Websites. Payment will follow within 10 business days after the end of the each month; provided, however, that payment will be made only when the minimum payout, based on net income, of $100.00 has been reached. Any amount below $100.00 will be carried over until the minimum payout has been reached and will be paid on the next following payment date. If you provide us with incorrect payment details, any fees for chargebacks resulting from such incorrect payment details will be offset against any amounts otherwise payable to you.</p>
        	<p>In the event you violate any part of these Terms of Services, you violate any third party right, including without limitation any copyright, property, or privacy right, or where a third party claims that all or any part of your Content caused it damage, we may, at our sole discretion, withhold indefinitely payments to you.</p>
        	<p>We remind you that it is only your duty and obligation to fulfill all tax obligations with regard to your activities for us, for example registration, declaration and payment obligations related to income taxes and VAT. If we assist you with these obligations, it does not release you from your obligations. It is your duty to inform us in a timely manner of changes to your personal data such as an address change or a new e-mail.</p>
        	<p>Where the Model is a taxable person for VAT purposes, they hereby authorize us to issue invoices in the name and on behalf of the Model (self-billing). Any Model who is a taxable person hereby confirms that they will not issue any VAT invoices for transactions under the Terms of Services and shall accept any such invoices issued on their behalf by us. In case of de-registration from VAT or in case of any changes of the Model’s status as a taxable person, they shall be obliged to notify us immediately. This self-billing agreement shall be effective for a period not exceeding 12 months.</p>
        	<p><span class="policyHeaders">Prohibited Uses</span></p>
        	<p>You agree that you will only use the Websites and our services for the lawful purposes expressly permitted and contemplated by these Terms of Service. You may not use the Websites and our services for any other purposes, including commercial purposes, without our express written consent.</p>
        	<p>You agree that you will view the Websites and its content unaltered and unmodified. You acknowledge and understand that you are prohibited from modifying the Websites or eliminating any of the content of the Websites, including ads. By using the Websites you expressly agree to accept advertising served on and through the Websites and to refrain from using ad blocking software or to disable ad blocking software before visiting the Websites.</p>
        	<p>You agree that you will not use or attempt to use any method, device, software or routine to harm others or interfere with the functioning of the Websites or use and/or monitor any information in or related to the Websites for any unauthorized purpose. Specifically, you agree not to use the Websites to:</p>
        	<p>• violate any law (including without limitation laws related to torts, contracts, patents, trademarks, trade secrets, copyrights, defamation, obscenity, pornography, rights of publicity or other rights) or encourage or provide instructions to another to do so;</p>
        	<p>• act in a manner that negatively affects other users’ ability to use the Websites, including without limitation by engaging in conduct that is harmful, threatening, abusive, inflammatory, intimidating, violent or encouraging of violence to people or animals, harassing, stalking, invasive of another’s privacy, or racially, ethnically, or otherwise objectionable;</p>
        	<p>• post any Content that depicts any person under 18 years of age (or older in any other location in which 18 is not the minimum age of majority);</p>
        	<p>• post any Content for which you have not maintained written documentation sufficient to confirm that all subjects of your posts are, in fact, over 18 years of age (or older in any other location in which 18 is not the minimum age of majority);</p>
        	<p>• post any Content depicting child pornography, rape, snuff, torture, death, violence, or incest, racial slurs or hate speech, (either aurally or via the written word);</p>
        	<p>• post any Content that contains falsehoods or misrepresentations that could damage the Websites or any third party;</p>
        	<p>• post any Content that is obscene, illegal, unlawful, defamatory, libelous, harassing, hateful, racially or ethnically offensive, or encourages conduct that would be considered a criminal offense, give rise to civil liability, violate any law, or is otherwise inappropriate;</p>
        	<p>• post any Content containing unsolicited or unauthorized advertising, promotional materials, spam, junk mail, chain letters, pyramid schemes or any other form of unauthorized solicitation;</p>
        	<p>• post any Content containing sweepstakes, contests, or lotteries, or otherwise related to gambling;</p>
        	<p>• post any Content containing copyrighted materials, or materials protected by other intellectual property laws, that you do not own or for which you have not obtained all necessary written permissions and releases;</p>
        	<p>• post any Content which impersonates another person or falsely state or otherwise misrepresent your affiliation with a person;</p>
        	<p>• deploy programs, software or applications designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment, including by engaging in any denial of service attack or similar conduct;</p>
        	<p>• deploy or use programs, software or applications designed to harm, interfere with the operation of, or access in an unauthorized manner, services, networks, servers, or other infrastructure;</p>
        	<p>• exceed your authorized access to any portion of the Websites;</p>
        	<p>• remove, delete, alter, circumvent, avoid or bypass any digital rights management technology, encryption or security tools used anywhere on the Websites or in connection with our services;</p>
        	<p>• collect or store personal data about anyone;</p>
        	<p>• alter or modify without permission any part of the Websites or its content, including ads;</p>
        	<p>• obtain or attempt to access or otherwise obtain any Content or information through any means not intentionally made available or provided for through the Websites;</p>
        	<p>• exploit errors in design, features which are not documented and/or bugs to gain access that would otherwise not be available.</p>
        	<p>Additionally, you agree not to:</p>
        	<p>• use the Websites in any manner that could disable, overburden, damage, or impair the site or interfere with any other party’s use of the Websites, including their ability to engage in real time activities through the Websites;</p>
        	<p>• use any robot, spider or other automatic device, process or means to access the Websites for any purpose, including monitoring or copying any of the material on the Websites without our prior written consent;</p>
        	<p>• use any manual process to monitor or copy any of the material on the Websites or for any other unauthorized purpose without our prior written consent;</p>
        	<p>• use any information obtained from or through the Websites to block or interfere with the display of any advertising on the Websites, or for the purpose of implementing, modifying or updating any software or filter lists that block or interfere with the display of any advertising on the Websites;</p>
        	<p>• use any device, bots, scripts, software or routine that interferes with the proper working of the Websites or that shortcut or alter Websites functions to run or appear in ways that are not intended by Websites design;</p>
        	<p>• introduce or upload any viruses, Trojan horses, worms, logic bombs, time bombs, cancelbots, corrupted files or any other similar software, program or material which is malicious or technologically harmful or that that may damage the operation of another’s property or of the Websites or our services;</p>
        	<p>• attempt to gain unauthorized access to, interfere with, damage or disrupt any parts of the Websites, the server on which the Websites is stored, or any server, computer or database connected to the Websites;</p>
        	<p>• remove any copyright or other proprietary notices from our Websites or any of the materials contained therein;</p>
        	<p>• attack the Websites via a denial-of-service attack or a distributed denial-of-service attack;</p>
        	<p>• otherwise attempt to interfere with the proper working of the Websites.</p>
        	<p><span class="policyHeaders">Monitoring and Enforcement; Termination</span></p>
        	<p>We have the right to:</p>
        	<p>• remove or refuse to post any Content you submit or contribute to the Websites for any or no reason in our sole discretion,</p>
        	<p>• take any action with respect to any Content posted by you that we deem necessary or appropriate in our sole discretion, including if we believe that such Content violates these Terms of Use, infringes any intellectual property right or other right of any person or entity, threatens the personal safety of users of the Websites or the public or could create liability for us,</p>
        	<p>• disclose your personally identifying information or other information about you to any third party who claims that Content posted by you violates their rights, including their intellectual property rights or their right to privacy,</p>
        	<p>• take appropriate legal action, including without limitation, referral to law enforcement, for any illegal or unauthorized use of the Websites,</p>
        	<p>• terminate or suspend your access to all or part of the Websites for any or no reason, including without limitation, any violation of these Terms of Service.</p>
        	<p>Without limiting the foregoing, we have the right to fully cooperate with any law enforcement authorities or court order requesting or directing us to disclose the identity or other information of anyone posting any Content on or through the Websites. YOU WAIVE AND HOLD US HARMLESS AND OUR SITE OPERATOR, ITS PARENT CORPORATION, THEIR RESPECTIVE AFFILIATES, LICENSORS, SERVICE PROVIDERS, OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, SUCCESSORS AND ASSIGNS FROM ANY CLAIMS RESULTING FROM ANY ACTION TAKEN BY US OR ANY OF THE FOREGOING PARTIES DURING OR AS A RESULT OF ITS INVESTIGATIONS AND FROM ANY ACTIONS TAKEN AS A CONSEQUENCE OF INVESTIGATIONS BY EITHER US, SUCH PARTIES OR LAW ENFORCEMENT AUTHORITIES.</p>
        	<p>To maintain our services in a manner we deem appropriate for our venue and to the maximum extent permitted by applicable laws, the Websites may, but will not have any obligation to, review, monitor, display, reject, refuse to post, store, maintain, accept or remove any Content posted (including, without limitation, private messages, public comments, public group chat messages, private group chat messages or private instant messages) by you, and we may, in our sole discretion, delete, move, re-format, remove or refuse to post or otherwise make use of Content without notice or any liability to you or any third party in connection with our operation of the Websites in an appropriate manner. Without limitation, we may do so to address Content that comes to our attention that we believe is offensive, obscene, violent, harassing, threatening, abusive, illegal or otherwise objectionable or inappropriate, or to enforce the rights of third parties or these Terms of Service or any applicable additional terms, including, without limitation, the Content restrictions set forth herein.</p>
        	<p>However, we do not undertake to review Content before it is posted on the Websites, and cannot ensure prompt removal of objectionable Content after it has been posted. Accordingly, we assume no liability for any action or inaction regarding transmissions, communications or Content provided by any user or third party. We have no liability or responsibility to anyone for performance or non-performance of the activities described in this section.</p>
        	<p><span class="policyHeaders">Account Termination Policy</span></p>
        	<p>While pornographic and adult-oriented Content is accepted, the Websites reserves the right to decide whether Content is appropriate or violates these Terms of Use for reasons other than copyright infringement and violations of intellectual property rights, such as, but not limited to, obscene or defamatory material. The Websites may at any time, without prior notice and in its sole discretion, remove such Content and/or terminate a user’s account for submitting such material in violation of these Terms of Use.</p>
        	<p>If you violate the letter or spirit of these Terms of Use, or otherwise create risk or possible legal exposure for us, we can terminate access to the Websites or stop providing all or part of the Websites to you.</p>
        	<p><span class="policyHeaders">Copyrights and Other Intellectual Property</span></p>
        	<p>The Websites respects the intellectual property of others, and requires that you do the same. You may not upload, embed, post, email, transmit or otherwise make available any Content that infringes any copyright, patent, trademark, trade secret, privacy, publicity or other proprietary rights of any person or entity.</p>
        	<p>The Websites operates a clear Copyright Policy in relation to any Content alleged to infringe the copyright of a third party. Details of that policy can be found at http://backpage.bit/information#dmca. If you believe that any Content violates your copyright, please see our Copyright Policy http://backpage.bit/information#dmca for instructions on sending us a notice of copyright infringement.</p>
        	<p>As part of our Copyright Policy, the Websites will terminate user access to the Websites if, under appropriate circumstances, a user has been determined to be a repeat infringer.</p>
        	<p>The Websites is not in a position to mediate trademark disputes between users and trademark owners. Accordingly, we encourage trademark owners to resolve any dispute directly with the user in question. If the trademark owner is unable to reach a resolution with the user, it may send us a notice at support@taboou.com. The Websites are willing to perform a limited investigation of reasonable complaints and will remove content in clear cases of infringement.</p>
        	<p><span class="policyHeaders">Reliance on Information Posted</span> </p>
        	<p>The information presented on or through the Websites is made available solely for general information purposes. We do not warrant the accuracy, completeness or usefulness of this information. Any reliance you place on such information is strictly at your own risk. We disclaim all liability and responsibility arising from any reliance placed on such materials by you or any other visitor to the Websites, or by anyone who may be informed of any of its contents.</p>
        	<p>This Websites include Content provided by third parties, including materials provided by other users, bloggers and third-party licensors, syndicators, aggregators and/or reporting services. All statements and/or opinions expressed in these materials, and all articles and responses to questions and other content, other than the content provided by us, are solely the opinions and the responsibility of the person or entity providing those materials. These materials do not necessarily reflect our opinion. We are not responsible, or liable to you or any third party, for the content or accuracy of any materials provided by any third parties.</p>

        	<p><span class="policyHeaders">Changes to the Websites</span></p>
        	<p>We may update the content on the Websites from time to time, but their content is not necessarily complete or up-to-date. Any of the material on the Websites may be out of date at any given time, and we are under no obligation to update such material.</p>
        	<p><span class="policyHeaders">Information about You and Your Visits to the Websites</span></p>
        	<p>All information we collect on the Websites is subject to our Privacy Policy https://backpage.bit/information#privacy. By using the Websites, you consent to all actions taken by us with respect to your information in compliance with the Privacy Policy.</p>
        	<p><span class="policyHeaders">Collection and Use of Your Usage Information by Advertisers and Others</span></p>
        	<p>The Websites allow others to display advertisements using the Websites. These third parties use technology to deliver advertisements you see using the Websites directly to your browser. In doing so, they may automatically receive your IP, or "Internet Protocol", address. Others that place advertising using the Websites may have the ability to use cookies and/or web beacons to collect information, including information about your usage of the Websites. We do not control the processes that advertisers use to collect information. However, IP addresses, cookies and web beacons alone generally cannot be used to identify individuals, only machines. Therefore, advertisers and others whose advertisements or content may be provided through the Service generally will not know who you are unless you provide additional information to them, by responding to an advertisement, by entering into an agreement with them, or by some other means.</p>
        	<p><span class="policyHeaders">Linking to the Websites and Social Media Features</span></p>
        	<p>You may link to the Websites, provided you do so in a way that is fair and legal and does not damage our reputation or take advantage of it, but you must not establish a link in such a way as to suggest any form of association, approval or endorsement on our part without our express written consent.</p>
        	<p>This Websites may provide certain social media features that enable you to:</p>
        	<p>• link from your own or certain third-party Websites to certain content on the Websites;</p>
        	<p>• send e-mails or other communications with certain content, or links to certain content, on the Websites;</p>
        	<p>• cause limited portions of content on the Websites to be displayed or appear to be displayed on your own or certain third-party Websites.</p>
        	<p>You may use these features solely as they are provided by us and solely with respect to the content they are displayed with and otherwise in accordance with any additional terms and conditions we provide with respect to such features. Subject to the foregoing, you must not:</p>
        	<p>• cause the Websites or portions of it to be displayed, or appear to be displayed by, for example, framing, deep linking or in-line linking, on any other site,</p>
        	<p>• otherwise take any action with respect to the materials on this Websites that is inconsistent with any other provision of these Terms of Service.</p>
        	<p>The Websites from which you are linking, or on which you make certain content accessible, must comply in all respects with the content standards set out in these Terms of Service.</p>
        	<p>You agree to cooperate with us in causing any unauthorized framing or linking immediately to cease. We reserve the right to withdraw linking permission without notice.</p>
        	<p>We may disable all or any social media features and any links at any time without notice in our discretion.</p>

        	<p><span class="policyHeaders">Links from the Websites</span></p>
        	<p>If the Websites contain links to other sites and resources provided by third parties, these links are provided for your convenience only. This includes links contained in advertisements, including banner advertisements and sponsored links. We have no control over, and assumes no responsibility for, the contents, privacy policies, or practices of those sites or resources, and accept no responsibility for them or for any loss or damage that may arise from your use of them. Inclusion of, linking to, or permitting the use or installation of any third party site, applications, software, content or advertising does not imply approval or endorsement thereof by us. If you decide to access any of the third party Websites linked to this Websites, you do so entirely at your own risk and subject to the terms and conditions of use for such Websites. Further, you agree to release us from any and all liability arising from your use of any third-party Websites, content, service, or software accessed through the Websites.</p>
        	<p>Your communications or dealings with, or participation in promotions of, sponsors, advertisers, or other third parties found through the Websites, are solely between you and such third parties. You agree that the Websites shall not be responsible or liable for any loss or damage of any sort incurred as the result of any dealings with such sponsors, third parties or advertisers, or as the result of their presence on the Websites.</p>
        	<p><span class="policyHeaders">Permitted Disclosures of Personal Information</span> </p>
        	<p>The Websites generally do not collect personally identifiable information (data such as your name, email address, password, and the content of your communications) unless you submit or communicate Content through the Websites, or register with us in order to use certain features of the Websites. The Websites will not disclose any personally identifiable information it collects or obtains except: (i) as described in these Terms of Use or our Privacy Policy; (ii) after obtaining your permission to a specific use or disclosure; (iii) if the Websites are required to do so in order to comply with any valid legal process or governmental request (such as a court order, search warrant, subpoena, civil discovery request, or statutory requirement); (iv) as required to protect the Websites’s property, safety, or operations, or the property or safety of others; or (v) to a person that acquires the Websites, or the assets of the Websites’s operator in connection with which such information has been collected or used; or (vi) as otherwise required by law.</p>

        	<p>$sIndemnification</p>

        	<p>To the extent permitted by applicable law, you agree to defend, indemnify and hold harmless the Websites, their site operator, their parent corporation, their respective affiliates, licensors, service providers, officers, directors, employees, agents, successors and assigns from and against any and all claims, damages, judgments, awards, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney’s fees) arising from: (i) your use of and access to the Websites; (ii) your violation of any term of these Terms of Use; (iii) your violation of any third party right, including without limitation any copyright, property, or privacy right; or (iv) any claim that your Content caused damage to a third party. This defense and indemnification obligation will survive these Terms of Use and your use of the Websites. You agree that we shall have the sole right and obligation to control the legal defense against any such claims, demands, or litigation, including the right to select counsel of our choice and to compromise or settle any such claims, demands, or litigation.</p>
        	<p><span class="policyHeaders">Disclaimers</span></p>

        	<p>YOU USE THE WEBSITES AT YOUR SOLE RISK. WE PROVIDE THE WEBSITES "AS IS" AND "AS AVAILABLE". TO THE FULLEST EXTENT PERMITTED BY LAW, THE WEBSITES, ITS SITE OPERATOR AND THEIR RESPECTIVE OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS EXPRESSLY DISCLAIM ALL WARRANTIES OF ANY KIND RELATED TO THE WEBSITES AND GOODS OR SERVICES PURCHASED AND OBTAINED THROUGH THE WEBSITES, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM YOUR USE OF THE WEBSITES.</p>
        	<p>WE MAKE NO WARRANTY OR REPRESENTATION ABOUT THE ACCURACY OR COMPLETENESS OF THIS WEBSITES’S CONTENT OR THE CONTENT OF ANY SITES LINKED TO THIS WEBSITES OR THAT THE WEBSITES WILL MEET YOUR REQUIREMENTS AND ASSUME NO LIABILITY OR RESPONSIBILITY FOR ANY (I) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT, (II) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF THE WEBSITES OR OUR SERVICES, (III) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN, (IV) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM THE WEBSITES OR OUR SERVICES, (IV) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE WHICH MAY BE TRANSMITTED TO OR THROUGH THE WEBSITES OR OUR SERVICES BY ANY THIRD PARTY, AND/OR (V) ANY ERRORS OR OMISSIONS IN ANY CONTENT OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF ANY CONTENT POSTED, EMAILED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE WEBSITES OR OUR SERVICES. THE WEBSITES DOES NOT WARRANT, ENDORSE, GUARANTEE, OR ASSUME RESPONSIBILITY FOR ANY PRODUCT OR SERVICE ADVERTISED OR OFFERED BY A THIRD PARTY THROUGH THE WEBSITES OR OUR SERVICES OR ANY HYPERLINKED SERVICES OR FEATURED IN ANY BANNER OR OTHER ADVERTISING, AND, THE WEBSITES WILL NOT BE A PARTY TO OR IN ANY WAY BE RESPONSIBLE FOR MONITORING ANY TRANSACTION BETWEEN YOU AND THIRD-PARTY PROVIDERS OF PRODUCTS OR SERVICES. AS WITH THE PURCHASE OF A PRODUCT OR SERVICE THROUGH ANY MEDIUM OR IN ANY ENVIRONMENT, YOU SHOULD USE YOUR BEST JUDGMENT AND EXERCISE CAUTION WHERE APPROPRIATE.</p>
        	<p>NO INFORMATION OBTAINED BY YOU FROM US OR THROUGH THE WEBSITES SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THESE TERMS.</p>
        	<p><span class="policyHeaders">Limitation of Liability</span></p>
        	<p>To the fullest extent allowed by law, the Websites, their site operator, their parent corporation and their respective officers, directors, employees, and agents shall not be responsible or liable to you for any loss or damage of any sort incurred as the result of the following:</p>
        	<p>• delaying, rejecting or removing any or all Content at any time for any or no reason whatsoever with or without notice to you,</p>
        	<p>• modifying or discontinuing temporarily or permanently, the Websites (or any part thereof) with or without notice to you for any or no reason whatsoever,</p>
        	<p>• immediately terminating your access to the Websites for any or no reason whatsoever and with or without notice to you,</p>
        	<p>• the accuracy, usefulness or availability of any information posted to or through the Websites,</p>
        	<p>• any user Content that does not get recorded, or is deleted, or for any similar unsatisfactory results or user Content,</p>
        	<p>• any errors or omissions in any Content or for any loss or damage of any kind incurred as a result of your use of any Content posted, emailed, transmitted, or otherwise made available via the Websites,</p>
        	<p>• personal injury or property damage, of any nature whatsoever, resulting from your access to and use of our Websites,</p>
        	<p>• any unauthorized access to or use of our secure servers and/or any and all personal information and/or financial information stored therein,</p>
        	<p>• any interruption or cessation of transmission to or from our Websites,</p>
        	<p>• any bugs, viruses, Trojan horses, or the like, which may be transmitted to or through our Websites by any third party, and/or</p>
        	<p>• any loss or damage of any sort incurred by you as a result of interactions you have with third-party advertisements or service providers, or third-party Websitess, found on or through the Websites, including payment and delivery of related goods or services, and any other terms, conditions, policies, warranties or representations associated with such dealings.</p>
        	<p>In no event shall we be liable to you for any incidental, indirect, punitive, statutory, exemplary, expectation, special, or consequential damages whatsoever (including damages for loss of profit, loss of goodwill, interruption, loss of business information or any other financial loss) in association with any individual or class-action claim, or any loss, damage, action, suit or other proceeding relating to or arising under or out of the Terms of Service, even if we have been notified of the possibility of such damages, whether the action is founded upon contract, infringement of intellectual property rights, tort, negligence or other grounds.</p>
        	<p>YOU SPECIFICALLY ACKNOWLEDGE THAT THE WEBSITES SHALL NOT BE LIABLE FOR CONTENT OR THE DEFAMATORY, OFFENSIVE, OR ILLEGAL CONDUCT OF ANY THIRD PARTY AND THAT THE RISK OF HARM OR DAMAGE FROM THE FOREGOING RESTS ENTIRELY WITH YOU.</p>
        	<p>THE FOREGOING LIMITATION OF LIABILITY SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW IN THE APPLICABLE JURISDICTION. YOU AGREE NOT TO FILE ANY LAWSUIT OR PROCEEDING INCONSISTENT WITH THE FOREGOING LIABILITY LIMITATIONS.</p>
        	<p><span class="policyHeaders">Governing Law</span></p>
        	<p>These Terms, your use of the Websites, and the relationship between you and us shall be governed by the laws of Cyprus, without regard to conflict of law rules. You agree that: the Websites shall be deemed passive Websites that does not give rise to personal jurisdiction over us, either specific or general, in jurisdictions other than Cyprus. The sole and exclusive jurisdiction and venue for any action or proceeding arising out of or related to this Agreement shall be in an appropriate court located in Limassol, Cyprus. You hereby submit to the jurisdiction and venue of said Courts. You consent to service of process in any legal proceeding.</p>
        	<p>Any claim by you that may arise in connection with these Terms will be compensable by monetary damages and you will in no event be entitled to injunctive or other equitable relief.</p>

        	<p><span class="policyHeaders">Limitation on Time to File Claims</span></p>
        	<p>REGARDLESS OF ANY STATUTE OR LAW TO THE CONTRARY, ANY CAUSE OF ACTION OR CLAIM YOU MAY HAVE ARISING OUT OF OR RELATING TO THESE TERMS OF SERVICE OR THE WEBSITES MUST BE COMMENCED WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES, OTHERWISE, SUCH CAUSE OF ACTION OR CLAIM IS PERMANENTLY BARRED.</p>
        	<p>DMCA</p>
        	<p>We respect the intellectual property rights of copyright holders, and thus will comply with the Notice and Takedown provisions of the Digital Millennium Copyright Act ("DMCA"). Our DMCA Notice Of Copyright Infringement can be found here.</p>

        	<p><span class="policyHeaders">Your Comments and Concerns</span></p>
        	<p>This Websites are operated by MG Freesites Ltd, Block 1, 195-197 Old Nicosia-Limassol Road, Dali Industrial zone, Cyprus 2540.</p>
        	<p>All notices of copyright infringement claims should be sent to the copyright agent designated in our Copyright Policy <a href="backpage.bit/information#dmca">http://backpage.bit/information#dmca</a> in the manner and by the means set forth therein.</p>
        	<p>All other feedback, comments, requests for technical support and other communications relating to the Websites should be directed to: <a href="mailto:support@taboou.com">support@taboou.com</a>.</p>
        	<p><span class="policyHeaders">Waiver and Severability</span></p>
        	<p>No waiver of by the Company of any term or condition set forth in these Terms of Use shall be deemed a further or continuing waiver of such term or condition or a waiver of any other term or condition, and any failure of the Company to assert a right or provision under these Terms of Use shall not constitute a waiver of such right or provision.</p>
        	<p>If any provision of these Terms of Use is held by a court or other tribunal of competent jurisdiction to be invalid, illegal or unenforceable for any reason, such provision shall be eliminated or limited to the minimum extent such that the remaining provisions of the Terms of Service will continue in full force and effect.</p>


        	<p><span class="policyHeaders">Entire Agreement</span></p>
        	<p>The Terms of Use, our Privacy Policy, our Copyright Policy and any documents they expressly incorporate by reference constitute the sole and entire agreement between you and us with respect to the Websites and supersede all prior and contemporaneous understandings, agreements, representations and warranties, both written and oral, with respect to the Websites.</p>
        	<p><span class="policyHeaders">Assignment</span></p>

        	<p>These Terms of Service, and any rights and licenses granted hereunder, may not be transferred or assigned by you, but may be assigned by us without restriction.</p>
        	<p><span class="policyHeaders">Fees</span></p>

        	<p>You acknowledge that the Websites reserves the right to charge for its services and to change its fees from time to time in its discretion. Furthermore, in the event the Websites terminates your rights to use the Websites because of a breach of these Terms of Services, you shall not be entitled to the refund of any unused portion of subscription fees.</p>
        	<p><span class="policyHeaders">Miscellaneous</span></p>

        	<p>No party, nor any of the parties’ respective attorneys, shall be deemed the drafter of this agreement for purposes of interpreting any provision hereof in any judicial or other proceeding that may arise between the parties.</p>
        	<p>Except as otherwise expressly provided in these Terms of Service, there shall be no third-party beneficiaries to this agreement. For the purpose of clarity, the Websites’s representatives, managers, partners, joint venturers, employees, and agents are intended third-party beneficiaries.</p>
        	<p>No agency, partnership, joint venture, employee-employer or franchiser-franchisee relationship is intended or created by these Terms of Service.</p>
        	<p>The headings in these Terms of Service are for convenience only and have no legal or contractual effect.</p>
        	<p>We may terminate these Terms of Service for any or no reason at any time by notifying you through a notice on the Websites, by email, or by any other method of communication. Any such termination will be without prejudice to our rights, remedies, claims, or defenses hereunder. Upon termination of the Terms of Service, you will no longer have a right to access your account or your Content. We will not have any obligation to assist you in migrating your data or your Content and we may not keep any back up of any of your Content. We will not be not responsible for deleting your Content. Note that, even if your Content is deleted from our active servers, it may remain in our archives (but we have no obligation to archive or back-up your Content), and subject to the licenses set forth in these Terms of Service.</p>
        </div>
    }

    componentDidMount() {
        /* Scroll to top. */
        $('html,body').scrollTop(0)
    }
}
